### PR TITLE
Update `neovim` to `0.9.1-1`

### PR DESCRIPTION
**Pull request by kavplex**

### CODE REVIEW

**Review by SonyStinks — APPROVED** [review]
Still good code...

**Comment by kavplex** [comment]
**Package publishing has failed @makedeb/prebuilt-mpr-reviewers!** Please look over the [Checks tab](/makedeb/prebuilt-mpr/pull/122/checks) to see what went wrong.

**Comment by SonyStinks** [comment]
We know it errors out. Hunter is working on this problem--it's not a real problem.
The thing merged just fine and it's only GitHub's growing pains throwing the error.

**Comment by kavplex** [comment]
Package publishing has succeeded! :tada:

**Pull request merged**
