### PR TITLE
Update `prismlauncher` to `7.1-1`

### PR DESCRIPTION
**Pull request by kavplex**

### CODE REVIEW

**Comment by hwittenborn** [comment]
Had to do this one more time because of a type, see #160.

**Comment by SonyStinks** [comment]
Is dada513 still maintaining this?

**Comment by lordofpipes** [comment]
> Is dada513 still maintaining this?

I'm the one who maintains it these days, been doing work to ensure ARM support and potentially adding more optional dependencies.

**Comment by hwittenborn** [comment]
Hey @lordofpipes! Now that you mention ARM stuff, the Prebuilt-MPR is actually in the works for getting arm64 support added.

Not sure if you're here because the Prebuilt-MPR package hasn't been updated yet (I saw that Prism Launcher just had a release), but jobs aren't currently running while arm64 support gets added. I plan on finishing that all up by the end of the day though, and then the package will be updated in here.

**Comment by lordofpipes** [comment]
Cool, thank you! It should be aarch64-ready right now, I did have to workaround https://github.com/makedeb/makedeb/issues/263 as the change hasn't been shipped in makedeb yet, by removing the x86-64 CFLAGS and adding some ARM (as well as riscv64 and armv7) flags, which seems to work.

This currently looks like this:

```bash
# allow for ARM support
#TODO: makedeb's hard-coding for x86-64 has been fixed in a future makedeb version
#TODO: these 6 lines make this script match the behavior of future makedeb. When it releases, remove this
CARCH="$(uname -p)"
CHOST="$(uname -p)-pc-linux-gnu"
CFLAGS=${CFLAGS/-march=x86-64/}
CXXFLAGS=${CXXFLAGS/-march=x86-64/}
CFLAGS=${CFLAGS/-mtune=generic/}
CXXFLAGS=${CXXFLAGS/-mtune=generic/}

# if the user hasn't specified a tuning/architecture, specify our own minimal defaults
if [[ ${CFLAGS} != *"-mtune"* && ${CFLAGS} != *"-march"* ]]; then
  case $(uname -m) in
    x86_64)
      CFLAGS+=" -march=x86-64 -mtune=generic"
      CXXFLAGS+=" -march=x86-64 -mtune=generic"
      ;;
    aarch64*|armv8*|armv9*|arm64*)
      CFLAGS+=" -march=armv8-a -mtune=generic"
      CXXFLAGS+=" -march=armv8-a -mtune=generic"
      ;;
    arm*)
      CFLAGS+=" -march=armv7-a -mtune=generic"
      CXXFLAGS+=" -march=armv7-a -mtune=generic"
      ;;
    riscv64*)
      CFLAGS+=" -march=rv64imafdc"
      CXXFLAGS+=" -march=rv64imafdc"
      CFLAGS=${CFLAGS/-fcf-protection/}
      CXXFLAGS=${CXXFLAGS/-fcf-protection/}
      ;;
  esac
fi
```

So let me know if this looks appropriate

**Comment by hwittenborn** [comment]
Hey I'm back! That makedeb bug definitely needs to get fixed sometime, I've just been crazy busy with other projects and haven't had a chance to get to it quite yet (I've actually made a fix in the `alpha` branch, I just haven't been able to get the fix merged into `beta` or `stable` yet).

The Prebuilt-MPR is using [this](https://github.com/makedeb/prebuilt-mpr/blob/172e25625731d33d31a56343582025bbac8b4a3b/.github/workflows/update-pkg.yml#L83-L135) as its `makepkg.conf` if you want to base it off of that (it's pretty much the stock config with compiler flags removed). I don't even know much of anything about the available C/C++ flags honestly - I haven't ever had to use them in practice. Compiling C libraries/binaries outside of makedeb always worked without manually setting them, so I just removed them from the Prebuilt-MPR workflows and everything seems to be working just fine still. The fix in the `alpha` branch actually does that, as I didn't see much merit in making the existing config work across multiple architectures when removing the values worked just fine.

**Comment by hwittenborn** [comment]
The Prebuilt-MPR update is also taking a bit longer than I was expecting, thought I'm hoping to finish it up by tomorrow. I don't want to make any guarantees, but I won't be doing much tomorrow besides that, so I'm expecting it to be completed then.

**Comment by lordofpipes** [comment]
> Compiling C libraries/binaries outside of makedeb always worked without manually setting them, so I just removed them from the Prebuilt-MPR workflows and everything seems to be working just fine still. The fix in the alpha branch actually does that, as I didn't see much merit in making the existing config work across multiple architectures when removing the values worked just fine.

This works, but AFAIK has the risk of producing non-generic builds that don't work on older CPUs. I have a specific project in mind to put together a bunch of unofficial PrismLauncher builds for different architectures and Linux distros, so that's why I'm trying to guarantee the builds are as generic as possible. This is overkill for most packages, so I generally agree with what you've done in makedeb's alpha branch..

**Comment by hwittenborn** [comment]
I didn't know that, thanks for the heads up though! If you or anyone else notices any issues with the Prebuilt-MPR packages on arm architectures (still yet to come out) definitely let me know and I'll get any changes to the config merged in.

**Comment by hwittenborn** [comment]
While I'm here though, would there be any interest in the Prebuilt-MPR containing PrismLauncher packages for anything other than `amd64` and `arm64`? I'm still in the middle of getting all of the Prebuilt-MPR packages built for other architectures, and right now would be a great time to add any other architectures if there'd be interest.

**Comment by lordofpipes** [comment]
> While I'm here though, would there be any interest in the Prebuilt-MPR containing PrismLauncher packages for anything other than `amd64` and `arm64`? I'm still in the middle of getting all of the Prebuilt-MPR packages built for other architectures, and right now would be a great time to add any other architectures if there'd be interest.

Sure! Only if you think the maintenance is worth it, of course. Currently, I have the package tested on:

- i386 (Debian 11 and 12)
- x86-64 (Debian 11 and 12, Ubuntu 22.04 and 23.04)
- ARMv7+fp (Debian 11 and 12, Ubuntu 22.04 and 23.04)
- ARMv8 (Debian 11 and 12, Ubuntu 22.04 and 23.04)
- RISC-V RV64G (Debian sid, will be available for Debian 13)

**Comment by hwittenborn** [comment]
Luckily there isn't much of a maintenance burden at this point for adding new architectures - I just add any architectures to a list and then the Prebuilt-MPR will just start building for it.

I don't remember if I mentioned it, but it looks like you know about makedeb using Docker to run builds on different architectures in GitHub Actions. The general approach I've gone with is support Ubuntu primarily, so I've thought of avoiding any architectures that aren't available via Ubuntu docker images. I'd be interested in adding architectures only available on Debian at some point in the future, but immediate plans are definitely only to do Ubuntu-supported architectures.

> x86 (Debian 11 and 12)

I would support that, but it's been of my knowledge that it's been fading out, and I don't have any known metrics stating it's that popular. Would this be something that you think would make a different for a good chunk of people?

> ARMv7+fp (Debian 11 and 12, Ubuntu 22.04 and 23.04)

The same logic applies for this I suppose (I guess `arm64` replaces it? I don't know how arm architecture versions work a ton), though I've kind of assumed it was pretty popular still. Is this just the `arm32v7` architecture on Docker Hub?

**Comment by hwittenborn** [comment]
Also, Prism Launcher is now being updated and built for `amd64` and `arm64` in #254. I wasn't sure if anyone on Prism Launcher's side was asking about, but I thought I'd let you know just in case.

**Comment by lordofpipes** [comment]
> I would support that, but it's been of my knowledge that it's been fading out, and I don't have any known metrics stating it's that popular. Would this be something that you think would make a different for a good chunk of people?

Yep, no x86-32 support on Ubuntu is a tricky one, and just in the past few months Debian developers have been saying they struggle to keep up with build failures slowly creeping up. The Pentium really is dying these days, so it is certainly less compelling to support.

> The same logic applies for this I suppose (I guess arm64 replaces it? I don't know how arm architecture versions work a ton), though I've kind of assumed it was pretty popular still. Is this just the arm32v7 architecture on Docker Hub?

ARMv7 got a lot of use in Android phones and a few development boards, but this architecture's only big foray into desktops was a few Samsung Chromebooks and Microsoft Surface tablets that were quickly replaced with x86-64 and ARMv8 equivalents. So yeah, it's not compelling either. But yeah, it's the `linux/arm/v7` architecture on Docker and I have this properly tested in Qemu.

**Pull request closed without merging**
