### PR TITLE
Update `prismlauncher` to `7.1-1`

### PR DESCRIPTION
**Pull request by kavplex**

### CODE REVIEW

**Comment by doonv** [comment]
You should update this to Prism Launcher 7.1

**Comment by hwittenborn** [comment]
Looks like there's some issue going on with the auto-updater @doonv, I'm getting it looked at real quick, and the package should be updated within the next 30 minutes or so.

**Comment by hwittenborn** [comment]
@doonv: I just need to figure out why the bullseye build is failing and then this should all be good to go

**Comment by hwittenborn** [comment]
I've thought about what I'd say to the PrismLauncher team, but there's no clean way this can be resolved until Debian Bullseye fixes the issue. I'm just gonna implement a patch manually into the Prebuilt-MPR codebase to fix the issue.

**Comment by hwittenborn** [comment]
Had to make new PR so the updated code could run, it can be found at #158.

**Pull request closed without merging**
